CREATE TABLE biblioteca
             (
                          id_biblioteca NUMBER generated BY DEFAULT AS identity PRIMARY KEY ,
                          nome          VARCHAR(100) NOT NULL
             );CREATE TABLE usuario
             (
                          matricula NUMBER PRIMARY KEY ,
                          nome      VARCHAR2(100) NOT NULL ,
                          telefone  VARCHAR2(20) ,
                          tipo      VARCHAR2(20) CHECK (tipo IN ('professor',
                                                                 'aluno',
                                                                 'funcionario')) NOT NULL ,
                          situacao_cadastral VARCHAR2(50) NOT NULL ,
                          id_biblioteca      NUMBER NOT NULL ,
                          FOREIGN KEY (id_biblioteca) REFERENCES biblioteca(id_biblioteca)
             );CREATE TABLE funcionario
             (
                          matricula NUMBER PRIMARY KEY ,
                          nome      VARCHAR2(100) NOT NULL
             );CREATE TABLE livro
             (
                          id_livro       NUMBER generated BY DEFAULT AS identity PRIMARY KEY ,
                          titulo         VARCHAR2(150) NOT NULL ,
                          editora        VARCHAR2(150) NOT NULL ,
                          ano_publicacao DATE NOT NULL ,
                          isbn           VARCHAR2(20) NOT NULL ,
                          qtd_exemplares NUMBER NOT NULL
             );CREATE TABLE exemplar
             (
                          id_exemplar     NUMBER generated BY DEFAULT AS identity PRIMARY KEY ,
                          data_aquisicao  DATE NOT NULL ,
                          disponibilidade VARCHAR2(20) NOT NULL ,
                          qtd_exemplares  NUMBER NOT NULL ,
                          id_livro        NUMBER NOT NULL ,
                          FOREIGN KEY (id_livro) REFERENCES livro(id_livro)
             );CREATE TABLE autor
             (
                          id_autor NUMBER generated BY DEFAULT AS identity PRIMARY KEY ,
                          nome     VARCHAR2(100) NOT NULL
             );CREATE TABLE categoria
             (
                          id_categoria NUMBER generated BY DEFAULT AS identity PRIMARY KEY ,
                          nome         VARCHAR2(100) NOT NULL
             );CREATE TABLE emprestimo
             (
                          id_emprestimo           NUMBER generated BY DEFAULT AS identity PRIMARY KEY ,
                          data_emprestimo         DATE NOT NULL ,
                          data_prevista_devolucao DATE NOT NULL ,
                          data_devolucao          DATE ,
                          atraso                  NUMBER ,
                          multa                   NUMBER (10, 2) ,
                          matricula_usuario       NUMBER NOT NULL ,
                          id_exemplar             NUMBER NOT NULL ,
                          FOREIGN KEY (matricula_usuario) REFERENCES usuario(matricula) ,
                          FOREIGN KEY (id_exemplar) REFERENCES exemplar(id_exemplar)
             ); COMMIT;
             
CREATE TABLE livro_autor
  (
     id_livro NUMBER NOT NULL,
     id_autor NUMBER NOT NULL,
     PRIMARY KEY (id_livro, id_autor),
     FOREIGN KEY (id_livro) REFERENCES livro(id_livro),
     FOREIGN KEY (id_autor) REFERENCES autor(id_autor)
  );

CREATE TABLE livro_categoria
  (
     id_livro     NUMBER NOT NULL,
     id_categoria NUMBER NOT NULL,
     PRIMARY KEY (id_livro, id_categoria),
     FOREIGN KEY (id_livro) REFERENCES livro(id_livro),
     FOREIGN KEY (id_categoria) REFERENCES categoria(id_categoria)
  );

CREATE TABLE funcionario_livro
  (
     matricula_funcionario NUMBER NOT NULL,
     id_livro              NUMBER NOT NULL,
     PRIMARY KEY (matricula_funcionario, id_livro),
     FOREIGN KEY (matricula_funcionario) REFERENCES funcionario(matricula),
     FOREIGN KEY (id_livro) REFERENCES livro(id_livro)
  );

CREATE TABLE funcionario_emprestimo
  (
     matricula_funcionario NUMBER NOT NULL,
     id_emprestimo         NUMBER NOT NULL,
     PRIMARY KEY (matricula_funcionario, id_emprestimo),
     FOREIGN KEY (matricula_funcionario) REFERENCES funcionario(matricula),
     FOREIGN KEY (id_emprestimo) REFERENCES emprestimo(id_emprestimo)
  ); COMMIT;